.github/dependabot.yml
.github/workflows/codeql.yml
.github/workflows/license_check.yml
.github/workflows/lint.yml
.github/workflows/scorecard.yml
.github/workflows/test.yml
.golangci.yml
CODEOWNERS
COPYRIGHT.txt
LICENSE
go.mod

Add basic CI, licensing, and CODEOWNERS

---

.github/workflows/license_check.yml

use sigstore/community impl of dependency-review

use community dependency review config

---

.github/workflows/test.yml
Dockerfile
compose.yml

Add compose.yml to easily start the GCP emulator services for development and CI. Adds an initial starting point for E2E tests.
Relates to https://github.com/sigstore/rekor-tiles/issues/6

Add docker compose file

---

.github/workflows/protoc_diff_check.yml

Action to ensure if someone changes protos, they also update generated code
NONE
NONE

Add action to check if protos have changes

---

.github/workflows/protoc_diff_check.yml
.gitignore
Makefile

Add licenses and goimports to `make lint` target
NONE
NONE

add more auto formatting

---

README.md

README.md: mention sigstore-dev to access docs

---

.vscode/settings.json

We added a freeze build tag recently.

Update build settings for new build tag

---

Dockerfile
Dockerfile.emulator_init
Makefile
tests/e2e_test.go

Also fixes e2e testing and `make all` on macOS, and fixes linting errors for Dockerfiles.
It appears that too many concurrent requests on macOS causes connections to get dropped. Not sure why, but a simple retry loop seems to resolve it.
Fixes https://github.com/sigstore/rekor-tiles/issues/173

Update to a multi-platform versioned gcloud container

---

.github/dependabot.yml

Dependabot can now keep container references up to date in Compose files, where we currently reference Spanner and GSC emulators. Also added a missing directory for the protoc-builder container.

Add docker-compose for dependabot, add folder for protoc dockerfile

---

.goreleaser.yaml

Log output noted these have been renamed.

Update deprecated goreleaser configs

---

.github/workflows/build_container.yml

The `event_name` is `push`, not `tag`. Since the only event to trigger this GHA is `push`, we can omit that. To differentiate between branch pushes and tags, we can use `github.ref`, which will either be `refs/heads/main` when pushed to main or `refs/tags/v1.2.3` for tags.

Change condition for building tagged container

---

.github/workflows/release.yml

Add comment for why we install Syft

---

Dockerfile

The build time is now down from 34 min to 10 min, but we were still installing dlv on a build platform that didn't match the runner platform. This change reuses the builder image, whose platform matches the runner, to cross-compile dlv, and then copy the binary over in a later stage.

Build dlv with cross-compilation

---

Dockerfile

When the build and target platform are the same, go install installs the binary under GOPATH/bin. If they differ, then it is installed under GOPATH/bin/TARGETOS_TARGETARCH. I didn't notice this in my local testing, since the build and target platforms of course matched. In CI, this caused an issue when the build platform (linux_amd64) did not match the target platform (linux_arm64), and the binary was installed in an unexpected directory.
Note that go install doesn't let you select output location, and go build doesn't let you target specific versions. There are feature requests for both of these.
Also copied in the ENV variables into the dlvbuilder stage, since ARG and ENV steps are not copied into later stages.

Fix cross-compilation for dlv binary for Docker

---

compose.yml

1.5.34@f98725ceb484500d858d17916ea4a04e2a83184b5a080a87113770e82c177744 is a multi-platform container for linux/amd64 and linux/arm64. I was getting issues running the previous digest locally on macOS (aka linux/arm64), that the platform wasn't supported.

Update digest for cloud-spanner-emulator

---

cmd/rekor-server/app/serve.go
compose.yml
go.mod
go.sum
pkg/server/grpc.go
pkg/server/grpcconfig.go
pkg/server/http.go
pkg/server/logging.go
pkg/server/service.go

use GCP-compatible structured logging

---

pkg/server/http.go

In GCP, it seems like this is necessary for the connection to succeed. Without this, the pod gets restarted since the liveness check fails. This does not reduce security since the TLS connection is over localhost.

Fix HTTP connection for gRPC over TLS

---

CLIENTS.md

Update clients documentation with API changes

---

compose.yml
config/emulator_init.sh
go.mod
tests/e2e_test.go

The missing feature in the Spanner emulator preventing Tessera from enabling deduplication functionality was resolved, so enable it by default in the docker compose file and add an end to end test for it.
Fixes https://github.com/sigstore/rekor-tiles/issues/158

Enable persistent antispam option

---

SHARDING.md

This includes the sharding playbook to be used by oncallers to spin up a new shard.
There's a TODO to add a dashboard link once we have monitoring, and WIPs as we are actively developing the prober and figuring out shard turn down.
Towards https://github.com/sigstore/rekor-tiles/issues/40

Create initial sharding playbook

---

cmd/rekor-server/app/otel.go
cmd/rekor-server/app/serve.go
go.mod

Tessera includes Open Telemetry instrumentation. This change sets up an exporter to automatically have Tessera metrics collected in GCP. This ignores Traces for now.
Partial https://github.com/sigstore/rekor-tiles/issues/225
Requires https://github.com/sigstore/terraform-modules/pull/69 before deployment.

Export Tessera Open Telemetry metrics

---

SHARDING.md

Fix https://github.com/sigstore/rekor-tiles/issues/495
We'll have a single status page entry for Rekor v2, and each time we turn down a shard, we'll update the underlying status page monitor to check the /healthz endpoint of the new shard.

sharding: Update monitor for status page

---

cmd/rekor-server/app/serve.go
internal/tessera/gcp.go
internal/tessera/tessera.go

Fixes https://github.com/sigstore/rekor-tiles/issues/428

Set user agent for GCP clients

---

SHARDING.md

This will enable the ArmoredWitness project to generate cosignatures for Rekor v2 shards.

Update omniwitness configuration while sharding

---

.github/workflows/release.yml

Add required runs-on for release approval
