sigstore/rekor-tiles

.github/workflows/license_check.yml

By default, the check can only run on pull requests. We can configure it to work by setting `base-ref`, but it's sufficient to have this as a required check on PR runs.

Update license check CI target

---

pkg/server/grpcconfig.go
pkg/server/grpcconfig_test.go
pkg/server/httpconfig.go
pkg/server/httpconfig_test.go

part of #82 
Configuration objects for setting up the http/grpc servers. Anything in `cmd` should populate these and send them over so stuff in `pkg` doesn't need to look into cmd line parameters.
NONE
NONE

Add options for configuring http/grpc

---

pkg/server/service.go

part of #82
~~requires #84~~
This just adds the server stubs as unimplemented functions. 
NONE
NONE

Add grpc stubs

---

cmd/rekor-server/app/serve.go
pkg/server/grpc.go
pkg/server/http.go
pkg/server/serve.go
pkg/server/serve_test.go
pkg/server/service_mock.go
pkg/server/service_test.go

Starts up servers and makes them available on localhost
todos:
- Add optional tls protection when communicating between http proxy and grpc service (see fulcio impl)
- Forward command line options to config objects (we use defaults)
Final part of #82
NONE
NONE

Add grpc and http servers.

---

pkg/server/grpc_test.go
pkg/server/grpcconfig.go
pkg/server/http.go
pkg/server/http_test.go
pkg/server/httpconfig.go
pkg/server/serve.go
pkg/server/service_mock.go

Also separate out http and grpc tests and create test fixtures for starting and stopping the server
Most of this is actually moving the tests around so we can check specific behaviors in each server type
NONE
NONE

Make bad http requests fail

---

.github/workflows/test.yml

* Enable oidc auth for codecov -- use a workaround since the actual auth mechanism is broken
* This adds `id-token: write` permission in the unit-tests job. I think this is ok: test.yml impersonation is not a big issue
* Also add `fail_ci_if_error: true` so we actually notice if the action fails -- we can revert this if failures turn out to be common
I expect that this will fix #104.

Codecov tweaks

---

pkg/server/http.go
pkg/server/service.go

Use HTTP 201 Created when an entry is successfully added.

Fix upload success status code

---

pkg/tessera/safeint.go
pkg/tessera/safeint_test.go
pkg/tessera/tessera.go

Expose the uint64<->int64 conversion type so it can be used more widely over the code base.

Make SafeInt64 public

---

cmd/rekor-server/app/serve.go
compose.yml
go.mod
go.sum
pkg/server/grpc.go
pkg/server/http.go
pkg/server/httpconfig.go
pkg/server/httpconfig_test.go
pkg/server/metrics.go
pkg/server/metrics_test.go
pkg/server/serve.go
pkg/server/service.go

Add default metrics to grpc and http servers
Add some rudimentary metrics for counting new entries
Serve metrics on (default) 0.0.0.0:2112 or <host>:<metrics-port>
fixes #124 
Adds prometheus config
Endpoints using configs should add new metric types to metrics, and increment them (or whatever) by using the singleton instance provided by `getMetrics()`
to see metrics in action:
```
docker-compose up
curl localhost:2112
```
NONE
NONE

Add metrics

---

pkg/tessera/tessera_test.go
pkg/types/dsse/dsse_test.go
pkg/types/hashedrekord/hashedrekord_test.go
pkg/types/verifier/verifier_test.go

`assert.Errorf` doesn't actually check the error message, `assert.ErrorContains` does that.

Fix unit test error checking

---

pkg/tessera/tessera.go
pkg/tessera/tessera_test.go

Also add failure case to the unit test.

Return canonicalized body in server response

---

.github/dependabot.yml

This only groups patch level updates: this might not do that much considering the inconsistent version numbering used in the relevant ecosystems... We could add "minor" updates too but then there's more chance of broken dependebot group updates

dependabot: Group patch updates

---

codecov.yml

This creates a decent amount of noisy comments on PRs. We have this off for other repos and codecov still works fine, generating reports for coverage for the PR.

Disable codecov patch updates

---

config/emulator_init.sh

Adds timestamps to init.sh
```
*  Executing task: docker logs --tail 1000 -f 1aa3ce4a772ac814f2ad823b8aed046933cf664b4b6d33ffdfd8d254925a1ee6 
+2025-03-24 20:09:31 21: gcloud config configurations list
+2025-03-24 20:09:31 21: grep emulator
+2025-03-24 20:09:31 21: grep True
+2025-03-24 20:09:34 21: gcloud config configurations create emulator
Created [emulator].
Activated [emulator].
+2025-03-24 20:09:35 22: gcloud config set auth/disable_credentials true
Updated property [auth/disable_credentials].
+2025-03-24 20:09:35 23: gcloud config set project rekor-tiles-e2e
Updated property [core/project].
+2025-03-24 20:09:36 24: gcloud config set api_endpoint_overrides/spanner http://spanner:9020/
WARNING: The value set for [api_endpoint_overrides/spanner] was found to be associated with a …
```

feat: add log timestamps to init.sh

---

pkg/client/option.go
pkg/client/read/read.go
pkg/client/read/read_test.go
pkg/client/transport.go
pkg/client/write/write.go
pkg/client/write/write_test.go

Add a client support package. This will be used in Rekor's integration tests and can be imported by Go-based Sigstore clients.
Depends on #119 
TODO:

Add client methods

---

cmd/rekor-server/app/serve.go
compose.yml
pkg/tessera/tessera.go
pkg/tessera/tessera_test.go

Expose Tessera's batch size, batch age, checkpoint interval, and pushback options through Rekor's configuration. This will enable us to tune the server to balance the cost and latency of sequencing entries, and in particular it will allow us to reduce the time to publish a new checkpoint so that entries added sequentially in tests no longer need to wait up to 10 seconds for a response.
Fixes https://github.com/sigstore/rekor-tiles/issues/148

Expose Tessera append lifecycle options

---

.vscode/settings.json

Without this the language server can't handle tests/e2e_tests.go from #128
(if everyone else is some kind of emacs wizard I can keep this to myself too)

build: Add vscode workspace settings

---

pkg/server/metrics_test.go

Fixes #162
This failure occurs because the HTTP latency and request metrics seem to be created only when a request has occurred.
When running all tests with go test ./..., no failure occurs, which is why CI didn't catch this. I believe this succeeded because another test triggered an HTTP request and however Prometheus is creating and scraping metrics created shared state between tests.

Fix metrics test failure when run by itself

---

.gitignore
cmd/rekor-server/app/serve.go
codecov.yml
pkg/server/grpc_test.go
pkg/server/serve.go
pkg/server/serve_test.go
pkg/server/service_mock.go
pkg/tessera/tessera.go

Fixes #138
When SIGTERM/SIGINT is sent to the process, which occurs when Kubernetes is shutting down pods, the server gracefully shuts down the gRPC and HTTP servers. Tessera also provides a shutdown function which will wait until a checkpoint has been published that covers all sequenced entries.
This change plumbs this shutdown function through to call it when the server is shutting down.

Shutdown Tessera gracefully on SIGTERM/SIGINT

---

.github/workflows/build_container.yml
Dockerfile

Fixes #169
More or less a copy-paste of GitHub's example config for generating a container image and publishing it to GHCR. It will be automatically tagged as main or vX.Y.Z depending on the event.
Also publishes Sigstore provenance to the container!

Add per-push and per-tag container build

---

.github/workflows/test.yml
cmd/freeze-checkpoint/app/root.go
cmd/freeze-checkpoint/main.go
cmd/rekor-server/app/serve.go
compose.yml
go.mod
pkg/note/note_test.go
pkg/server/http.go
pkg/server/service.go
pkg/server/service_test.go
pkg/signerverifier/file.go
pkg/signerverifier/file_test.go
pkg/signerverifier/signerverifier.go
pkg/signerverifier/tink.go
pkg/signerverifier/tink_test.go
tests/freeze-test.sh
tests/freeze_test.go

Add a flag that, when Rekor is restarted, prevents the service from accepting new entries or publishing new checkpoints. Add a command to publish a final checkpoint that contains an extension indicating the log is frozen.
Technically Rekor could be fully shut down and it would accomplish the same purpose of not accepting new entries or updating new checkpoints. The server change is mostly useful in the potential future when Rekor needs to be responsible for serving checkpoints stored in MySQL. The freeze command is necessary no matter the backend.
Fixes https://github.com/sigstore/rekor-tiles/issues/14
To do:

Add support for freezing the log

---

pkg/server/http.go
pkg/server/http_test.go

The Grpc-Metadata-Content-Type header was still present in the HTTP response, this removes it.
Fixes #97

Delete remaining gRPC headers from HTTP response

---

cmd/rekor-server/app/serve.go
pkg/algorithmregistry/algorithmregistry.go
pkg/algorithmregistry/algorithmregistry_test.go
pkg/server/service.go
pkg/server/service_test.go
pkg/types/dsse/dsse.go
pkg/types/dsse/dsse_test.go
pkg/types/hashedrekord/hashedrekord.go
pkg/types/hashedrekord/hashedrekord_test.go

Port over the configurable hash algorithms and key validation from
sigstore/rekor PR 1974. This both introduces a flag to restrict the
allowed signing algorithms for entries being submitted, as well as
validation to ensure the key used is within established constrictions
for the specified algorithm.
Much of this was borrowed from Rekor v1 with some modifications to
account for the different structure in rekor-tiles. Testing was done
here as unit tests rather than porting the script for the integration
tests from that PR.
Fixes https://github.com/sigstore/rekor-tiles/issues/100

Add entry hash algorithm config and validation

---

pkg/server/metrics.go
pkg/server/service.go
pkg/server/service_mock.go
pkg/tessera/tessera.go
pkg/types/dsse/dsse.go
pkg/types/hashedrekord/hashedrekord.go
pkg/types/validator/validator.go
protoc-builder/Dockerfile
protoc-builder/Makefile
tests/e2e_test.go

All TODOs now have an issue linked to make sure they're followed up on. This also resolves one TODO to use the healthcheck endpoint instead of just waiting a second.

Link TODOs to issues, ping healthz during mock server startup

---

.github/workflows/build_container.yml
.github/workflows/release.yml
.gitignore
.goreleaser.yaml
Dockerfile.release
Makefile

This adds a goreleaser script for publishing binaries. The binaries will
be indirectly signed from the GHA provenance.
Also updates the existing container release script to treat tags and
pushes separately, using a different Dockerfile with a minimal base
image.
Fixes https://github.com/sigstore/rekor-tiles/issues/198
Signed-off-by: Hayden B <8418760+haydentherapper@users.noreply.github.com>

Add release scripts for production binaries and containers 

---

.github/workflows/build_container.yml

Reused an identifier twice, can't do that.

Fix build container workflow

---

pkg/server/grpc.go
pkg/server/metrics.go
pkg/server/metrics_test.go

Handles when grpc processing panics
ref: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/main/examples/server/main.go#L111

Add panic interceptor and metrics for it

---

.github/workflows/build_container.yml

The ID was changed for two steps to be unique, but this broke attestation publishing. Couldn't find a good way to reference output across multiple steps, besides bash, so a little duplication is cleaner.

Fix container release workflow

---

pkg/server/grpc.go
pkg/server/grpcstats.go
pkg/server/http.go
pkg/server/metrics.go
pkg/server/metrics_test.go

Uses grpc stats to get measurement information on payload sizes
Interceptors don't provide wiresize of payloads. StatsHandler appears to be the right place to get this info, so we grab it from there.

Measure request payload sizes

---

api/proto/rekor_service.proto
docs/openapi/rekor_service.swagger.json
pkg/generated/protobuf/rekor_service.pb.go
pkg/generated/protobuf/rekor_service.pb.gw.go
pkg/generated/protobuf/rekor_service_grpc.pb.go
pkg/server/grpc_test.go
pkg/server/http_test.go
pkg/server/service.go
pkg/server/service_mock.go

Per C2SP/tlog-tiles, N should be encoded as zero-padded 3 digit path elements. While we could provide an API that takes an unsigned int as the index instead, this API would differ from how clients access tiles and entry bundles in GCS, which would be a leaky abstraction.
This change also simplifies the read API to remove separate APIs for partial tile requests, instead having the client encode the requested partial width in N as per C2SP/tlog-tiles.
Fixes #218

Change N to be an encoded index for read APIs

---

pkg/algorithmregistry/algorithmregistry.go
pkg/types/dsse/dsse.go
pkg/types/dsse/dsse_test.go
pkg/types/hashedrekord/hashedrekord.go
pkg/types/hashedrekord/hashedrekord_test.go
pkg/types/verifier/verifier.go
pkg/types/verifier/verifier_test.go

Cleans up ToLogEntry for hashedrekord and dsse to try to make it more
explicit that the function is doing both request validation and
verificaction of entry signatures. Hashedrekord refactored very easily,
but DSSE is a bit more tricky given the repeated verifiers. May come
back to this later.
For now, refactored extracted functions remain unexported as an external
use case is not yet known.
Fixes https://github.com/sigstore/rekor-tiles/issues/178

Refactor ToLogEntry, extract validators and verifiers

---

pkg/algorithmregistry/algorithmregistry.go
pkg/algorithmregistry/algorithmregistry_test.go
pkg/types/dsse/dsse.go
pkg/types/dsse/dsse_test.go

As described in the linked issue, clients cannot use the payload hash
when verifying signatures since there's no guarantee that the payload
hash algorithm matches the signature digest algorithm. Therefore, we can
simplify the payload hash output to just use a fixed digest. We pick the
hash alg that matches the leaf hash alg.
Fixes https://github.com/sigstore/rekor-tiles/issues/226
Signed-off-by: Hayden B <8418760+haydentherapper@users.noreply.github.com>

Simplify payload hash calculation for DSSE

---

.github/workflows/release.yml
.goreleaser.yaml

Drops unnecessary goarm as we only build for arm64, and build everything in the same directory to simplify the glob pattern.

Update release workflow to support macOS builds

---

pkg/server/metrics.go
pkg/server/service.go
pkg/tessera/tessera.go

This should always be zero, and we'll set up alerting for it.
Fixes #202

Add metric for inclusion proof verification failures

---

pkg/verify/verify.go
pkg/verify/verify_test.go

These will be used by log monitors and/or witnesses to verify consistency proofs, which the client is required to build.
Fixes #197

Add consistency proof verification functions

---

pkg/algorithmregistry/algorithmregistry.go
pkg/algorithmregistry/algorithmregistry_test.go
pkg/types/dsse/dsse.go
pkg/types/dsse/dsse_test.go
pkg/types/hashedrekord/hashedrekord.go
pkg/types/hashedrekord/hashedrekord_test.go

This adds the RSA key size or ECDSA curve name for easier debugging. Otherwise, we only get the signature and hash algorithms and can't match the rejection to a specific PublicKeyDetails.

Better logging for unsupported signature algorithm

---

cmd/rekor-server/app/serve.go
pkg/tessera/gcp.go
pkg/tessera/tessera.go
pkg/tessera/tessera_test.go

As future Tessera backends are added, each will need its own antispam initialization.
This also changes the default values for antispam pushback and max batch size to 0. When zero, the Tessera library will set the default. This is needed because each antispam backend has its own defaults.

Move antispam initialization under GCP backend

---

.github/workflows/build_container.yml
Dockerfile
Dockerfile.release
protoc-builder/Dockerfile

Fixes #229
Following this example:
https://docs.docker.com/build/building/multi-platform/#cross-compiling-a-go-application
Rather than use QEMU to launch an ARM build environment, which is incredibly slow on GitHub Actions, this uses Go's native cross compilation to build for multiple platforms. The builder is pinned to the build platform, Linux, while the target platform is passed to the Go builder as an OS and architecture.
Ko wasn't used because it doesn't build a multi-platform image, it builds an image per platform.
Also bumped Go to the latest version.

Use Go cross-compiler rather than emulated build platform

---

pkg/tessera/tessera.go
pkg/tessera/tessera_test.go

To produce strings in Rekor v1 responses, all hashes were hex-encoded. When the protobuf specs were created, rather than specify strings for hashes, we specified bytes. This fixes the root hash of the inclusion proof to be a byte array (and when marshalled to JSON, it will be base64-encoded).
This is another example of what should be updated with a TLE v2, dropping log index (specified in the bundle), root hash and tree size (both specified in the checkpoint). I'll update the client spec to recommend ignoring these fields.

Fix root hash as bytes rather than hex-encoded

---

pkg/server/http.go
tests/e2e_test.go

When we were deploying the service to staging, we noticed that the read APIs were returning 200 with an empty body for some reason. The root cause is due to how we handle returning an Unimplemented gRPC status code.
In order to return the non-retryable 405 Method Not Allowed when the server goes into a read-only mode, we added special handling when the gRPC status code is set to Unimplemented. Otherwise, it returns a 501 Not Implemented, which is not an accurate status for when the server is read-only.
When the status code is Unimplemented, we set the response code and body in the httpResponseModifier function based on internally-set gRPC headers. This worked correctly for the read-only response. However, for the 3 unimplemented read APIs, while we were setting a gRPC response code of …

Return 501 Method Not Implemented for read APIs

---

cmd/rekor-server/app/serve.go
pkg/note/note.go
pkg/note/note_test.go
pkg/server/service.go
pkg/server/service_test.go
pkg/tessera/tessera_test.go
tests/e2e_test.go

Fixes #285
To minimize the transition for clients between Rekor v1 and v2, we will
include the log ID in the response. This log ID is used by clients to
look up the correct instance in a trust root, though some clients ignore
it and build a pool of verification keys instead, and compare a
truncated log ID to the checkpoint signature key prefix.
I've chosen to make the log ID equal to the non-truncated checkpoint key
ID. For clients that treat the log ID as an opaque string when looking
up the instance in the trusted root, no changes should be needed.
Similarly, if a client uses the log ID to compare against the checkpoint
key ID, like what sigstore-python does, no changes are needed.
In the TransparencyLogInstance in the trusted root, both the log ID and
checkpoint key ID will be set to …

Add log ID to TransparencyLogEntry response, TLE testing in e2e test

---

protoc-builder/Makefile
protoc-builder/python-requirements.txt

https://github.com/sigstore/rekor-tiles/issues/289
Followup to #303 
Fixes the option for specifying pydantic types.
- https://github.com/danielgtaylor/python-betterproto/blob/124613f55fa8ff62a460e1ad33c5c78723b703a0/README.md#generating-pydantic-models
> With the important change being --python_betterproto_opt=pydantic_dataclasses. This will swap the dataclass implementation from the builtin python dataclass to the pydantic dataclass. You must have pydantic as a dependency in your project for this to work.
The existing code doesn't produce an error, but here's a sample of the different results with the new change
```python
-from dataclasses import dataclass
+from typing import TYPE_CHECKING
+
+
+if TYPE_CHECKING:
+    from dataclasses import dataclass
+else:
+    from …
```

fix pydantic generation

---

cmd/rekor-server/app/serve.go
pkg/server/http.go
pkg/server/httpconfig.go
pkg/server/httpconfig_test.go
pkg/server/service_mock.go

GCP requires that when the front load balancer is HTTPS and the request is over gRPC, then the connection between the load balancer and service backend must be over TLS as well. This is not true for HTTP traffic, where the front load balancer can be HTTPS but the connection between the load balancer and service backend can be over HTTP.
This PR splits the TLS flags into separate gRPC and HTTP flags so that deployers can selectively enable TLS for each serving path. Also this PR declares the flags, which previously were not declared.
There are existing tests that TLS works as expected. Updating the service mock to use the gRPC credentials makes the TLS tests pass.

Split TLS flags into separate gRPC and HTTP flags

---

api/proto/entry.proto
api/proto/rekor_service.proto
docs/openapi/rekor_service.swagger.json
pkg/generated/protobuf/entry.pb.go
pkg/generated/protobuf/rekor_service.pb.go

this is causing complications is some json converters (betterproto?) so lets just keep it simple.

Remove json_name from proto message fields

---

go.mod

This adds a retract directive to prevent pkg.go.dev from serving the accidental v0.99.0 tag.

Retract accidental tag

---

CLIENTS.md

The payload hash for a DSSE entry is always SHA-256. This was done to avoid needing a selection algorithm to pick a digest when multiple signature algorithms are used.

Update clients doc for DSSE verification

---

SHARDING.md

Added a step to set up the monitoring (which can likely be applied earlier in the process, for now we'll do it after spinning up the service) and switching to using a script for generating Tink keysets

Update sharding for metrics and tinkey

---

Dockerfile

Add /usr/bin/sleep so that the Kubernetes preStop hook can call it.
Partial https://github.com/sigstore/rekor-tiles/issues/370

Add sleep binary to image

---

SHARDING.md

create-tink-keyset now outputs both the checkpoint key ID and the public key formatted exactly as the trusted root expects them.

Update sharding with updated create-tink-keyset args

---

internal/server/service.go
internal/server/service_test.go

We've seen instances of client-side request cancellations from GitHub Actions, which has caused a bunch of unexpected 500s in the log.
When a context cancellation occurs, this will now be a client error (499) rather than an internal server error (500).

Handle context cancel during entry upload

---

.github/workflows/codeql.yml

Remove autobuild step: init can handle that
There's one fewer dependency to update like this (number of PRs sadly does not go down).

workflows: Remove unnecessary step from codeql

---

.github/workflows/build_container.yml
.github/workflows/release.yml

Currently releasing requires separate approval for both release and the docker image upload
* Make build_container.yml not run on tag push, but make it callable from release.yml
* Add build-container job into release.yml
* Add approval job to release.yml (needed by release and build-container)
This way build_container does not need an environment check at all:
* either it is running on push to main (in which case it won't push an image)
* or it is running by workflow_call and expects the caller to do the check (as release.yml does)
---
Fixes #498, maybe. Obviously I can't really test this in any way... But it looks like it could work. 
CC @haydentherapper

workflows: Streamline release
